{
    'name': 'Les infos des surveillants',
    'description': "Les infos des surveillants",
    'author': "Mejri Takwa",
    'maintainer': 'DIGIMOOV',
    'category': 'Partner',
    'sequence': 17,
    'summary': 'Les infos des surveillants',
    'depends': [
        'base',
        'contacts',
        'account',
        'mcm_session',
        'partner_exam',
        'sale',
        'account',
        'crm',
        'mcm_add_fields',
        'examen_cma_fields',
        'plateforme_pedagogique',
        'account_reports',
        'calendly_api_integration',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/inherit_partner_view.xml',
        'views/surveillants_view.xml',
        'views/inherit_session_view.xml',
        'views/inherit_views_partner_set_invisible_fields.xml',
    ],
    'qweb': [],
    'images': [],
    'demo': [
    ],
    'test': [
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
