from . import sendinblue_lists
from . import sendinblue_accounts
from . import mass_mailing_contact
from . import mass_mailing_list
from . import sendinblue_template
from . import mass_mailing
from . import mass_mailing_list_contact_rel
from . import res_partner
from . import sendinblue_folders
from . import sendinblue_merge_fields
from . import sendinblue_senders
from . import sendinblue_queue_process